//
// Created by Tobiathan on 11/3/21.
//

#ifndef SENIORRESEARCH_ANIMATIONCONTROLLER_H
#define SENIORRESEARCH_ANIMATIONCONTROLLER_H


class AnimationController {

};


#endif //SENIORRESEARCH_ANIMATIONCONTROLLER_H
